{"name": "test_create_auth_with_excel", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('read_credentials_from_excel', <FixtureRequest for <Function test_create_auth_with_excel>>)", "trace": "file E:\\The TESTING ACADEMY\\API_AUTOMATION\\Py3xAPIAutomationFramework\\tests\\tests\\datadriventesting\\test_ddt_for.py, line 38\n  def test_create_auth_with_excel(read_credentials_from_excel):\nE       fixture 'read_credentials_from_excel' not found\n>       available fixtures: _session_faker, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, create_token, doctest_namespace, extra, extras, faker, get_booking_id, include_metadata_in_junit_xml, metadata, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, testrun_uid, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, worker_id\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nE:\\The TESTING ACADEMY\\API_AUTOMATION\\Py3xAPIAutomationFramework\\tests\\tests\\datadriventesting\\test_ddt_for.py:38"}, "start": 1723190100338, "stop": 1723190100338, "uuid": "03f876dd-127a-4ceb-8ce5-0caf2ac6c35b", "historyId": "b0739cc2358249bd9122159058a2c32a", "testCaseId": "b0739cc2358249bd9122159058a2c32a", "fullName": "tests.tests.datadriventesting.test_ddt_for#test_create_auth_with_excel", "labels": [{"name": "parentSuite", "value": "tests.tests.datadriventesting"}, {"name": "suite", "value": "test_ddt_for"}, {"name": "host", "value": "LAPTOP-BELRSIMA"}, {"name": "thread", "value": "22940-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests.datadriventesting.test_ddt_for"}]}